# Kafka Configuration
kafka.bootstrap.servers=kafka:29092
kafka.group.id=fuel-price-processor
kafka.topic=fuel-prices
enable.auto.commit=false
auto.offset.reset=earliest

# PostgreSQL Configuration
# Docker service name: postgres-database
jdbc.url=jdbc:postgresql://postgres-database:5432/fuel_prices
jdbc.username=postgres
jdbc.password=123456