# Kafka Configuration
kafka.bootstrap.servers=localhost:9092
kafka.group.id=fuel-price-processor
kafka.topic=fuel-prices
enable.auto.commit=false
auto.offset.reset=earliest

# PostgreSQL Configuration
# Khi chạy trong Docker: thay localhost → postgres-database
jdbc.url=jdbc:postgresql://localhost:5432/fuel_prices
jdbc.username=postgres
jdbc.password=123456