apiVersion: 1

datasources:
  - name: Taobao ClickHouse
    uid: taobao-clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: ${CLICKHOUSE_GRAFANA_URL}
    jsonData:
      defaultDatabase: ${CLICKHOUSE_DATABASE}
      port: 8443
      protocol: http
      secure: true
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
    user: ${CLICKHOUSE_USER}
